en:
  locale: en-us
  title: Makarenko Alexandra
  contentDir: content/en
  params:
    description: Personal academic portfolio of Alexandra Makarenko
  menu:
    main:
      - name: Bio
        url: /
        weight: 10
      - name: Blog
        url: blog/
        weight: 15
      - name: Experience
        url: experience/
        weight: 20
      - name: Projects
        url: projects/
        weight: 30

ru:
  locale: ru-ru
  title: Макаренко Александра
  contentDir: content/ru
  params:
    description: Персональный сайт Макаренко Александры
  menu:
    main:
      - name: Обо мне
        url: /
        weight: 10
      - name: Блог
        url: blog/
        weight: 15
      - name: Опыт
        url: experience/
        weight: 20
      - name: Проекты
        url: projects/
        weight: 30
